### ISSUE TITLE
Sketch uses 112% of program storage

### ISSUE THREAD

**Issue by elik745i** [AlexNS/xiaomi-temperature-mqtt-example#1]
I tried to compile it for ESP32 DEVBOARDV1 but got error:

Sketch uses 1468849 bytes (112%) of program storage space. Maximum is 1310720 bytes.

Can you optimmize the sketch so it fits in DEVV1 boards too?

**Comment by AlexNS** [comment]
I'm afraid I can't. Sketch does quite a lot of different things and uses a lot of different libraries, so it is really hard to reduce code usage. I would recommend to use board with more flash.
Or it might be I have not enough knowledge for that :(
